apiVersion: apps/v1
kind: Deployment
metadata:
  name: proper-solution
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: proper-solution
        image: proper-solution:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
